name: "Coding Style Check"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Installation of node"
        uses: "actions/setup-node@v2"
        with:
          node-version: "16.16.0"

      - name: "yarn install"
        run: "yarn install"

      - name: "Check typescript coding style"
        run: "yarn eslint -c .ts-eslintrc.json files/**/*.ts"
